"""
Django settings for OnlineStudy project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#把子应用全部移动到一个包里方便管理，必须要这样设置，否则没有这个会报没有找到users（在operitaion中有引用users）模块
sys.path.insert(0,os.path.join(BASE_DIR,"apps"))
# sys.path.insert(0,os.path.join(BASE_DIR,"extra_apps"))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c_n=(b7+wq-l%(55noh1tg$^*3z5@=958pd2%nsuv&o0ebl!99'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',#用户模块
    'courses',#课程模块
    'organization',#培训机构模块
    'operation',#用户操作的相关模块
    'xadmin',#后台xadmin
    'crispy_forms',
    'captcha',#验证码
    'DjangoUeditor',#富文本

]
#我们继承了auth_user表
AUTH_USER_MODEL="users.UserProfile"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OnlineStudy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OnlineStudy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
#mysql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "onlinestudy",
        "HOST":"localhost",
        "USER":"root",
        "PASSWORD":"123456",
        "PORT":3306
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'#简体中文
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai' #时间为上海时间
USE_I18N = True

USE_L10N = True
# USE_TZ = True
USE_TZ = False #不是用默认时区


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
#第一种
# STATICFILES_DIRS=(os.path.join(BASE_DIR,"static"),)
#第二种
STATICFILES_DIRS=[os.path.join(BASE_DIR,"static"),]

#设置图片和文件上传路径
MEDIA_URL="/media/" #文件上传路径
MEDIA_ROOT=os.path.join(BASE_DIR,"static")#图片上传路径

#实现自定义登录方式(用户名或邮箱等其他方式)
AUTHENTICATION_BACKENDS=("users.views.CustomBackend",)

#captcha验证码设置

# 设置 captcha 图片大小
CAPTCHA_IMAGE_SIZE = (80, 40)
# 字符个数
CAPTCHA_LENGTH = 4
# 超时(minutes)
CAPTCHA_TIMEOUT = 1

#django配置邮件发送
EMAIL_HOST="smtp.163.com"
EMAIL_PORT=25
EMAIL_HOST_USER="aiduhuihuang@163.com"
EMAIL_HOST_PASSWORD="duhuihuang1988"
EMAIL_USE_TLS=False
EMAIL_FROM="aiduhuihuang@163.com"
#控制导航条那个高亮
Flag=0
#文件夹说明
"""
log:日志文件夹
media:用户上传文件的文件夹
static:静态文件的文件夹
templates:页面存放文件夹
"""