# Generated by Django 2.2.1 on 2020-03-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20200323_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
