# Generated by Django 2.2.1 on 2020-03-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('desription', models.CharField(max_length=400, verbose_name='课程描述')),
                ('detail', models.TextField(verbose_name='课程详情')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=6, verbose_name='课程难度')),
                ('learn_times', models.IntegerField(default=0, verbose_name='学习时长/分钟')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('image', models.ImageField(default='course/default.png', upload_to='course', verbose_name='课程封面图')),
                ('tag', models.CharField(default='', max_length=100, verbose_name='课程标签')),
                ('click_total', models.IntegerField(default=0, verbose_name='课程总点击数')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='课程添加时间')),
                ('need_know', models.CharField(max_length=300, verbose_name='课程须知')),
                ('teacher_tell', models.CharField(max_length=300, verbose_name='老师告诉你')),
            ],
            options={
                'verbose_name_plural': '课程',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课类别')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='类别描述')),
            ],
            options={
                'verbose_name_plural': '课程类别',
                'db_table': 'coursetype',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='章节名')),
                ('desription', models.CharField(blank=True, max_length=400, null=True, verbose_name='章节内容介绍')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name_plural': '章节信息',
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='视频名')),
                ('pathaddress', models.CharField(default='', max_length=300, verbose_name='播放地址')),
                ('learn_time', models.IntegerField(default=0, verbose_name='学习时长/分钟')),
                ('desription', models.CharField(blank=True, max_length=400, null=True, verbose_name='视频内容介绍')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节')),
            ],
            options={
                'verbose_name_plural': '章节视频',
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='视频名')),
                ('download', models.FileField(upload_to='up_file/resource', verbose_name='课程资源文件')),
                ('download_num', models.IntegerField(default=0, verbose_name='下载次数')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name_plural': '课程资源文件',
                'db_table': 'courseresource',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='catory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseType', verbose_name='课类别'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseorg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='机构'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='教师'),
        ),
    ]
